hero_description: |-
  **Autowelt** — продаж автомобілів із США та Європи по найкращих цінах
  Підбір, покупка, пригон, розмитнення
  *м. Львів вул. Городоцька, 300 (ТЦ МЕТРО)*
phone: "+380972552020"
footer_call_button_text: "Подзвоніть нам"
footer_map_button_text: "Ми на карті"
footer_copyright_text: "AutoWelt. Всі права захищено."
where_to_find_us:
  directions_title: "Наш автомайданчик у Львові"
  directions_text: >
    Вул. Городоцька, 300 - на території ТЦ "МЕТРО".
    При заїзді у головні ворота на територію ТЦ, їдете прямо поки не побачите нашу вивіску "AutoWelt" по ліву руку.

  # Google Maps embed URL (best: paste the "Embed a map" link here)
  map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1703.3278671558746!2d23.91530147782372!3d49.82204796128234!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473ae16b85d3cb2f%3A0xf73a51a9509cee1e!2zQXV0byBXZWx0INCQ0LLRgtC-INC3INCh0KjQkCDRliDQhNCy0YDQvtC_0Lg!5e1!3m2!1sen!2sua!4v1770833960239!5m2!1sen!2sua"
  value_title: "AutoWelt це не тільки продаж авто"
  value_text: >
    Ми надаємо послуги прозорого підбору авто. Перевірка, документи, розмитнення, супровід.
    Ми володієм доступом до закритих аукціонів у США де закупляєм автомобілі без пошкоджень.
    Також, великий вибір автомобілів в наявності із страхових аукціонів США та Європи по найкращих цінах у Львові.
  socials_title: "Слідкуйте ближче за подіями на майданчику"
  socials:
    instagram: "https://instagram.com/auto_welt_lviv"
    tiktok: "https://tiktok.com/@autowelt_lviv"
    telegram: "https://t.me/autowelt_lviv"

  photos:
    - "https://res.cloudinary.com/dpllddkot/image/upload/v1770834191/photo_2026-02-11_20.21.25_dg3cyi.jpg"
    - "https://res.cloudinary.com/dpllddkot/image/upload/v1770834192/photo_2026-02-11_20.21.32_omt6t5.jpg"
    - "https://res.cloudinary.com/dpllddkot/image/upload/v1770834192/photo_2026-02-11_20.21.28_gdshfk.jpg"